spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:13306/fail?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul}
    username: ${MYSQL_USERNAME:fail}
    password: ${MYSQL_PASSWORD}

server:
  port: 18080

jwt:
  secret: ${JWT_SECRET}
  refresh-cookie-secure: ${JWT_REFRESH_COOKIE_SECURE:false}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
